// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffjmeyyhnxhnjepjlonr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmam1leXlobnhobmplcGpsb25yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NTU4NzIsImV4cCI6MjA1NTAzMTg3Mn0.ON-Qfj2mMxUy0Cke1epi_NZJYOfcZXVmtHsntmXaxMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);